version: '3'

services:
  doorlock:
    image: doorlock
    container_name: doorlock
    restart: on-failure
    volumes:
      - ldap:/var/lib/ldap
    ports:
      - "5683:5683/udp"

volumes:
  ldap:
