version: '3'

services:
  tv:
    image: phdays_ctf_tv:v2
    container_name: tv
    working_dir: /opt/tv
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/tv
    command: bash start.sh
