version: '3'

services:
  mqtt-db:
    image: mqtt-db
    build:
      context: mqtt-db
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    hostname: mqtt-db
    container_name: mqtt-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306"

  mosquitto-auth-plugin:
    build:
      context: mosquitto-auth-plugin
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: mosquitto-auth-plugin
    container_name: mosquitto-auth-plugin
    volumes:
      - mosquitto-auth-plugin:/auth-plugin
    command: cp /usr/mosquitto-auth-plug/auth-plug.so /auth-plugin

  mqtt-broker:
    build:
      context: mosquitto
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: mosquitto
    hostname: mqtt-broker
    container_name: mqtt-broker
    depends_on:
      - mqtt-db
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-auth-plugin:/auth-plugin:ro
    links:
      - mqtt-db

#  sensor:
#    image: thermometer-sensor
#    hostname: sensor
#    container_name: sensor
#    depends_on:
#      - mqtt-broker
#    command: ["wait-for-it.sh", "-t", "0", "mqtt-broker:1883", "--", "/usr/bin/thermometer"]

volumes:
  mysql-data:
  mosquitto-auth-plugin:
