version: '3'

services:
  mqtt-db:
    image: thermometer/mqtt-db
    build:
      context: mqtt-db
      args:
        - http_proxy
        - https_proxy
        - no_proxy

  mqtt-broker:
    image: thermometer/mqtt-broker
    build:
      context: mosquitto
      args:
        - http_proxy
        - https_proxy
        - no_proxy

  sensor:
    image: thermometer/sensor
    build:
      context: sensor
      args:
        - http_proxy
        - https_proxy
        - no_proxy

  module:
    image: thermometer/module
    build:
      context: module
      args:
        - http_proxy
        - https_proxy
        - no_proxy
