version: '3'
services:
  mqtt-db:
    image: "mysql:latest"
    hostname: mqtt-db
    container_name: mqtt-db
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: kooj2ahj0eelaipeicahquiGehahsho1
      MYSQL_DATABASE: mqtt
  mosquitto-db-init:
    build: mosquitto-db-init
    image: mosquitto-db-init
    container_name: mosquitto-db-init
    depends_on:
      - mqtt-db
    links:
      - mqtt-db
    environment:
      MYSQL_ROOT_PASSWORD: kooj2ahj0eelaipeicahquiGehahsho1
    volumes:
      - ./mosquitto-db-init/scripts:/scripts
    command: bash -c "wait-for-it.sh -t 0 mqtt-db:3306 -- mysql --host=mqtt-db --port=3306 --user=root --password=kooj2ahj0eelaipeicahquiGehahsho1 mqtt < /scripts/init-db.sql"
  mqtt-broker:
    build: mosquitto
    image: mosquitto
    hostname: mqtt-broker
    container_name: mqtt-broker
    depends_on:
      - mqtt-db
      - mosquitto-db-init
    ports:
      - "1883:1883"
    links:
      - mqtt-db
    command: ["wait-for-it.sh", "-t", "0", "mqtt-db:3306", "--", "mosquitto", "-v", "-c", "/etc/mosquitto/mosquitto.conf"]
#  sensor:
#    image: thermometer-sensor
#    hostname: sensor
#    container_name: sensor
#    depends_on:
#      - mqtt-broker
#    command: ["wait-for-it.sh", "-t", "0", "mqtt-broker:1883", "--", "/usr/bin/thermometer"]
