version: '3'

services:
  mqtt-db:
    image: thermometer/mqtt-db
    hostname: mqtt-db
    container_name: mqtt-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306"

  mqtt-broker:
    image: thermometer/mqtt-broker
    hostname: mqtt-broker
    container_name: mqtt-broker
    depends_on:
      - mqtt-db
    ports:
      - "1883:1883"
    links:
      - mqtt-db

  sensor:
    image: thermometer/sensor
    hostname: sensor
    container_name: thermometer-sensor
    depends_on:
      - mqtt-broker
    links:
      - mqtt-broker

  module:
    image: thermometer/module
    hostname: module
    container_name: thermometer-module
    depends_on:
      - mqtt-broker
    links:
      - mqtt-broker
    ports:
      - "8888:8888"

volumes:
  mysql-data:
