version: '3'
services:
  mqtt-db:
    image: "mysql:latest"
    hostname: mqtt-db
    container_name: mqtt-db
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: kooj2ahj0eelaipeicahquiGehahsho1
      MYSQL_DATABASE: mqtt
      MYSQL_USER: mqtt_broker
      MYSQL_PASSWORD: UFRzFk2Lw5dd9h4u
  mqtt-broker:
    image: mosquitto
    hostname: mqtt-broker
    container_name: mqtt-broker
    depends_on:
      - mqtt-db
    ports:
      - "1883:1883"
    links:
      - mqtt-db
    environment:
      DB_USER: mqtt
      DB_PASSWORD: UFRzFk2Lw5dd9h4u
    command: ["wait-for-it.sh", "-t", "0", "mqtt-db:3306", "--", "mosquitto", "-v", "-c", "/etc/mosquitto/mosquitto.conf"]
  sensor:
    image: thermometer-sensor
    hostname: sensor
    container_name: sensor
    depends_on:
      - mqtt-broker
    command: ["wait-for-it.sh", "-t", "0", "mqtt-broker:1883", "--", "/usr/bin/thermometer"]
