- name: Download and install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.12.0/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
