---

- name: Copy fridge service from host
  copy:
    src: ../services/fridge
    dest: /home/ctf/
    owner: ctf
    group: ctf

- name: Build fridge containers
  command: /usr/bin/docker-compose -f /home/ctf/fridge/docker-compose.yml build

- name: Copy fridge systemd script
  copy:
    src: files/fridge.service
    dest: /etc/systemd/system

- name: Enable fridge service
  systemd:
    name: fridge
    enabled: yes
    state: started
    daemon_reload: yes
