---

- name: Copy fridge service from host
  copy:
    src: ../services/fridge
    dest: /home/user/
    owner: user
    group: user

- name: Build containers
  command: /usr/bin/docker-compose -f /home/user/fridge/docker-compose.yml build

#- name: Copy systemd script
#  copy:
#    src: files/fridge.service
#    dest: /etc/systemd/system

#- name: Force systemd to reread configs
#  systemd: daemon_reload=yes
#  changed_when: false

#- name: Enable fridge service
#  systemd:
#    name: fridge
#    enabled: yes
#    state: started
